file:
  db: null
  backup: true
  indent: 2
pager:
  enable: false
  command: null
  styles: true
view:
  default: null
  group_by: project
  sort_by: created_at
  stats:
    enable: default   # always / never / default / all
    count: filtered   # filtered / all
  history:
    max_length: 20
    num_components: 2
    timedelta: null
action:
  editor: null
token:
  id: '..'
  status: ','
  separator: '.'
  project: '/'
  tag: '@'
  priority: '!'
  deadline: '^'
  sort: '='
  query: '?'
  description: ':'
  stdin: '-'
alias:
  status:
    a: archive
    p: pending
    n: note
    d: done
    c: done
    x: delete
  title: {}
  tag:
    fav: like
    favorite: like
    heart: like
  priority:
    h: high
    n: normal
    l: low
message:
  empty: ':dizzy: [italic yellow]Nothing to show.[/]'
  add: '🪄 [italic green]Added 1 item.[/]'
  no_edit: ':thinking_face: [italic yellow]Nothing to update.[/]'
  edit: ':crystal_ball: [italic cyan]Updated {} {}.[/]'
  undo: ':hourglass_flowing_sand: [italic blue]Commit `{}` undone with change:[/]'
  redo: ':hourglass_flowing_sand: [italic blue]Commit `{}` redone with change:[/]'
  undo_add: ':boom: [italic red]Removed 1 item[/]'
  undo_edit: ':hourglass_flowing_sand: [italic cyan]Updated {} {}.[/]'
group:
  format:
    id: '{id}{status}{title}{project}{tags}{priority}{deadline}{description}'
    status: '{id}{title}{project}{tags}{priority}{deadline}{description}'
    project: '{id}{status}{title}{tags}{priority}{deadline}{description}'
    tag: '{id}{status}{title}{project}{priority}{deadline}{description}'
    priority: '{id}{status}{title}{project}{tags}{deadline}{description}'
    deadline: '{id}{status}{title}{project}{tags}{priority}{description}'
    created_at: '{.group.format.id}'
  header:
    format: '[bold]{group}[/] [dim]{progress}[/]'
    priority:
      high: '[magenta]{.item.priority.format.high} high[/]'
      normal: '. normal'
      low: '[dim]{.item.priority.format.low} low[/]'
    status:
      pending: '[yellow]{.item.status.format.pending} pending[/]'
      done: '[green]{.item.status.format.done} done[/]'
      note: '[blue]{.item.status.format.note} note[/]'
      archive: '[dim]{.item.status.format.archive} archived[/]'
    deadline:
      num_components: 1
      timedelta: 'yMwd'
item:
  format: '{.group.format.id}'
  id:
    format: '[dim]{:>4}.[/]'
  status:
    format:
      pending: '[bold yellow]☐[/]'
      done: '[bold green]✔[/]'
      note: '[bold blue]•[/]'
      delete: '[bold red]✘[/]'
      archive: '[bold dim]-[/]'
  title:
    format:
      status_done: '[strike dim]{}[/]'
      status_archive: '[strike dim]{}[/]'
      priority_high: '[bold magenta]{}[/]'
      priority_low: '[dim]{}[/]'
      tags_star: '[bold underline yellow]{}[/]'
      tags_like: '[bold underline magenta]{}[/]'
    max_length: 0
    ellipsis: …
  tag:
    format:
      _: '[blue]{.token.tag}[underline]{}[/][/]'
      _untagged: '[italic dim]Untagged[/]'
      star: '[bold yellow]★[/]'
      like: '[bold magenta]❤[/]'
  project:
    default: '{.token.project}inbox'
    format: '[bold]{.token.project}{}[/]'
  priority:
    format:
      high: '[bold magenta]{.token.priority}[/]'
      low: '[dim]⌄[/]'
      normal: ''
  deadline:
    format:
      status_done: '[dim]{}[/]'
      2592000: '[green]{}[/]'
      604800: '[cyan]{}[/]'
      86400: '[magenta]{}[/]'
      3600: '[yellow]{}[/]'
      0: '[red]{}[/]'
      _: '[blue]{}[/]'
    timedelta: null
    num_components: 2
    datetime: '%y-%b-%-d'
  created_at:
    format: '[dim]{:%y-%b-%-d %H:%M}[/]'
  description:
    format: '[italic dim]{}[/]'
    max_length: 30
    ellipsis: …
  diff:
    format: '[bold red]{{[/][strike dim]{}[/] [bold]→[/] {}[bold red]}}[/]'
stats:
  title:
    all: '{} of all tasks complete.'
    filtered: '{} of filtered tasks complete.'
  progress:
    10: '[bold red]{}[/]'
    25: '[bold yellow]{}[/]'
    50: '[bold magenta]{}[/]'
    75: '[bold blue]{}[/]'
    90: '[bold cyan]{}[/]'
    _: '[bold green]{}[/]'
  separator: ' · '
  status:
    pending: '[yellow]{.item.status.format.pending} {}[/] pending'
    done: '[green]{.item.status.format.done} {}[/] done'
    note: '[blue]{.item.status.format.note} {}[/] notes'
    archive: '[dim]{.item.status.format.archive} {}[/] archived'
    hidden: '[dim]◌ {}[/] hidden'
